# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.
systemProp.https.protocols=TLSv1.2,TLSv1.3
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=7890
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=7890

# Project
version=4.0.7
group=com.panicnot42.warp_book
java_version=21

# Common
minecraft_version=1.21
mod_name=Warp Book
mod_author=DarkgreenWorld, Panicnot42, FerreusVeritas, MelonVRneu, ArcAnc
mod_id=warp_book
license=GPL-3.0-only
credits=Claude Opus 5.5, Gemini 3.1 Pro Preview, UtmostStar
description=Magic book which allows you to make magical teleports.
minecraft_version_range=[1.21, 1.21.2)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21-20240613.152323
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21
parchment_version=2024.11.10

# Fabric
fabric_version=0.102.0+1.21
fabric_loader_version=0.16.9

# Forge
forge_version=51.0.33
forge_loader_version_range=[51,)

# NeoForge
neoforge_version=21.0.164
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G -Dhttps.protocols=TLSv1.2,TLSv1.3
org.gradle.daemon=false
