pluginManagement {
    repositories {
        // Mirrors carried over from the multiloader project
        maven { url = 'https://maven.aliyun.com/repository/gradle-plugin' }
        maven { url = 'https://maven.aliyun.com/repository/public' }
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        gradlePluginPortal()
        mavenCentral()
    }
}

// Should match the folder name of the project, or IDEA may complain
rootProject.name = 'WarpBook'
