pluginManagement {
    repositories {
		mavenLocal()
        maven { 
			name = 'MinecraftForge'
			url = 'https://maven.aliyun.com/repository/public' 
		}
        gradlePluginPortal()
        maven {
            name = 'MinecraftForge'
            url = 'https://maven.minecraftforge.net/'
        }
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_PROJECT)

    repositories {
        mavenLocal()
        maven { url = 'https://maven.aliyun.com/repository/public' }
        maven { url = 'https://maven.minecraftforge.net/' }
        mavenCentral()
    }
}

//plugins {
//    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.7.0'
//}
